### ISSUE TITLE
ValueError: `dataset` input should have multiple elements.

### ISSUE THREAD

**Issue by kdelint** [sb43/BAGELp#1]
Does anyone know what's causing this error?

File "c:\users\k.lint\appdata\local\programs\python\python36-32\lib\multiprocessing\pool.py", line 644, in get    raise self._value
ValueError: `dataset` input should have multiple elements.

[BagelP_errormsg.txt](https://github.com/sb43/BAGELp/files/2630306/BagelP_errormsg.txt)

**Comment by sb43** [comment]
I think this is related to gaussian_kde method in scipy:
https://github.com/scipy/scipy/issues/1694
https://github.com/scipy/scipy/commit/f01c0264

**Comment by kdelint** [comment]
Taking out genes from the reference essentials and nonessentials (CEG2 and NEG) that are not present in the sgRNA library (tested using TKOv1) solved this issue.

**Comment by sb43** [comment]
Thanks for digging into the issue
